### ISSUE TITLE
Reports not generating for GenomeConnect

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/genomeconnect-report#4]
@KelseaChang5 @larrybabb 

Not sure who to tag here but just wanted to report that it doesn't seem the GenomeConnect reports are populating in the folders as expected (https://console.cloud.google.com/storage/browser/clinvar-reports/GCReports_02-14-2022?orgonly=true&project=clingen-dev&supportedpurview=organizationId&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)

Just want to check if the path/location has changed

**Comment by dazzariti** [comment]
@larrybabb I reached out to Jules and she said it's ok to wait a week or two for the reports

**Comment by larrybabb** [comment]
@dazzariti I manually ran the genomeconnect reports and they can be found here https://console.cloud.google.com/storage/browser/clinvar-reports/GCReports_02-28-2022?project=clingen-dev&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

**Comment by larrybabb** [comment]
For the time being I will run these manually. I will need to find time to look into why the automated process is failing. It may be due to the fact that the files are getting larger and the report process is timing out before it completes.
